train:
  model_path: "weights/August/encroachment_onm_14August_Weights/weights/encroachment_onm_14August_Weights.pt"     # base pretrained model
  data_yaml: "dataset/encroachment_onm_14August/data.yaml"       # dataset config
  epochs: 10
  imgsz: 640

predict:
  model_path: "models/latest/best.pt"  # trained model to use
  conf_threshold: 0.25
  imgsz: 640
  source: "data/test/images"


